[package]
name = "medical_records"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]


[dependencies]
soroban-sdk.workspace = true
stellar-xdr = { version = "20.1.0", default-features = false, features = [] }



[dev-dependencies]
soroban-sdk = { workspace = true, default-features = false }


[features]
default = []
testutils = ["soroban-sdk/testutils"]

# No arbitrary or other extra features enabled
